# ----------------------- #
#      Main Configs       #
# ----------------------- #

# Site Settings
locale: "pt-BR"
name: "Dayana Couto - Coach de Carreira"
url: https://dayanacouto.com.br
title: Dayana Couto - Coach de Carreira
email: dayanaclf@gmail.com
author: Dayana Couto - Coach de Carreira
description: "Coach profissional,Palestrante e Analista Comportamental pelo Instituto Brasileiro de Coaching e, em breve, Practitioner em Programação Neurolinguística pelo Instituto Rompendo Limites, especializada em desenvolvimento profissional. Criadora do Programa PróCarreira, com mais de  80 horas de atuação contribuindo para potencializar pessoas para serem (mais) felizes, especialmente em suas carreiras, florescendo vida na vida delas!" 
copyright: 'Copyright &copy; 2020 - Dayana Couto - Coach de Carreira. Todos os direitos reservados.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: instagram
    url: https://www.instagram.com/_dayanaccoach/
  - title: whatsapp
    url: https://api.whatsapp.com/send?phone=5531988637943
  - title: facebook
    url: https://www.facebook.com/dayanaccoach
  - title: linkedin
    url: https://www.linkedin.com/in/dayana-couto-10ab727b/

destination: _site

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

plugins:
  - jekyll-seo-tag